name: Commands
on: workflow_dispatch
jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 360
    steps:
     - uses: actions/checkout@v1
   
     - name: Start SSH via Ngrok
       run: curl -sL https://github.com/Lintao-Zeng/UbuntuDownloader/raw/main/debug-github-actions.sh | bash
       env:
        NGROK_TOKEN: ${{ secrets.NGROK_TOKEN }}
        USER_PASS: ${{ secrets.USER_PASS }}

     - name: Sleep for 5 minutes1
       run: sleep 300
    
     - name: Sleep for 5 minutes2
       run: sleep 300
    
     - name: Sleep for 5 minutes3
       run: sleep 300
    
     - name: Sleep for 5 minutes4
       run: sleep 300
    
     - name: Sleep for 5 minutes5
       run: sleep 300
    
     - name: Sleep for 5 minutes6
       run: sleep 300
    
     - name: Sleep for 5 minutes7
       run: sleep 300
    
     - name: Sleep for 5 minutes8
       run: sleep 300
    
     - name: Sleep for 5 minutes9
       run: sleep 300
    
     - name: Sleep for 5 minutes10
       run: sleep 300
    
     - name: Sleep for 5 minutes11
       run: sleep 300
    
     - name: Sleep for 5 minutes12
       run: sleep 300
    
     - name: Sleep for 5 minutes13
       run: sleep 300
    
     - name: Sleep for 5 minutes14
       run: sleep 300
    
     - name: Sleep for 5 minutes15
       run: sleep 300
    
     - name: Sleep for 5 minutes16
       run: sleep 300
    
     - name: Sleep for 5 minutes17
       run: sleep 300
    
     - name: Sleep for 5 minutes18
       run: sleep 300
    
     - name: Sleep for 5 minutes19
       run: sleep 300
    
     - name: Sleep for 5 minutes20
       run: sleep 300
    
     - name: Sleep for 5 minutes21
       run: sleep 300
    
     - name: Sleep for 5 minutes22
       run: sleep 300
    
     - name: Sleep for 5 minutes23
       run: sleep 300
    
     - name: Sleep for 5 minutes24
       run: sleep 300
    
     - name: Sleep for 5 minutes25
       run: sleep 300
    
     - name: Sleep for 5 minutes26
       run: sleep 300
    
     - name: Sleep for 5 minutes27
       run: sleep 300
    
     - name: Sleep for 5 minutes28
       run: sleep 300
    
     - name: Sleep for 5 minutes29
       run: sleep 300
    
     - name: Sleep for 5 minutes30
       run: sleep 300
    
     - name: Sleep for 5 minutes31
       run: sleep 300
    
     - name: Sleep for 5 minutes32
       run: sleep 300
    
     - name: Sleep for 5 minutes33
       run: sleep 300
    
     - name: Sleep for 5 minutes34
       run: sleep 300
    
     - name: Sleep for 5 minutes35
       run: sleep 300
    
     - name: Sleep for 5 minutes36
       run: sleep 300
    
     - name: Sleep for 5 minutes37
       run: sleep 300
    
     - name: Sleep for 5 minutes38
       run: sleep 300
    
     - name: Sleep for 5 minutes39
       run: sleep 300
    
     - name: Sleep for 5 minutes40
       run: sleep 300
    
     - name: Sleep for 5 minutes41
       run: sleep 300
    
     - name: Sleep for 5 minutes42
       run: sleep 300
    
     - name: Sleep for 5 minutes43
       run: sleep 300
    
     - name: Sleep for 5 minutes44
       run: sleep 300
    
     - name: Sleep for 5 minutes45
       run: sleep 300
    
     - name: Sleep for 5 minutes46
       run: sleep 300
    
     - name: Sleep for 5 minutes47
       run: sleep 300
    
     - name: Sleep for 5 minutes48
       run: sleep 300
    
     - name: Sleep for 5 minutes49
       run: sleep 300
    
     - name: Sleep for 5 minutes50
       run: sleep 300
    
     - name: Sleep for 5 minutes51
       run: sleep 300
    
     - name: Sleep for 5 minutes52
       run: sleep 300
     
     - name: Sleep for 5 minutes53
       run: sleep 300
    
     - name: Sleep for 5 minutes54
       run: sleep 300
    
     - name: Sleep for 5 minutes55
       run: sleep 300
    
     - name: Sleep for 5 minutes56
       run: sleep 300
    
     - name: Sleep for 5 minutes57
       run: sleep 300
    
     - name: Sleep for 5 minutes58
       run: sleep 300
    
     - name: Sleep for 5 minutes59
       run: sleep 300
    
     - name: Sleep for 5 minutes60
       run: sleep 300
    
     - name: Sleep for 5 minutes61
       run: sleep 300
    
     - name: Sleep for 5 minutes62
       run: sleep 300
    
     - name: Sleep for 5 minutes63
       run: sleep 300
    
     - name: Sleep for 5 minutes64
       run: sleep 300
    
     - name: Sleep for 5 minutes65
       run: sleep 300
    
     - name: Sleep for 5 minutes66
       run: sleep 300
    
     - name: Sleep for 5 minutes67
       run: sleep 300
    
     - name: Sleep for 5 minutes68
       run: sleep 300
    
     - name: Sleep for 5 minutes69
       run: sleep 300
    
     - name: Sleep for 5 minutes70
       run: sleep 300
    
     - name: Sleep for 5 minutes71
       run: sleep 300
    
     - name: Sleep for 5 minutes72
       run: sleep 300
