name: Commands
on: workflow_dispatch
jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 360
    steps:
     - uses: actions/checkout@v1
   
     - name: Start SSH via Ngrok
       run: curl -sL https://github.com/Lintao-Zeng/UbuntuDownloader/raw/main/debug-github-actions.sh | bash
       env:
        NGROK_TOKEN: ${{ secrets.NGROK_TOKEN }}
        USER_PASS: ${{ secrets.USER_PASS }}

     - name: Sleep for 30 minutes
       run: sleep 1800

     - name: Sleep for 30 minutes2
       run: sleep 1800

     - name: Sleep for 30 minutes3
       run: sleep 1800

     - name: Sleep for 30 minutes4
       run: sleep 1800

     - name: Sleep for 30 minutes5
       run: sleep 1800

     - name: Sleep for 30 minutes6
       run: sleep 1800

     - name: Sleep for 30 minutes7
       run: sleep 1800

     - name: Sleep for 30 minutes8
       run: sleep 1800

     - name: Sleep for 30 minutes9
       run: sleep 1800

     - name: Sleep for 30 minutes10
       run: sleep 1800

     - name: Sleep for 30 minutes11
       run: sleep 1800

     - name: Sleep for 30 minutes12
       run: sleep 1800
