name: danted socks5 Proxy Server
on: workflow_dispatch
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
     - uses: actions/checkout@v1
   
     - name: Start SSH via Ngrok
       run: curl -sL https://github.com/Lintao-Zeng/UbuntuDownloader/raw/main/debug-github-actions4.sh | bash
       env:
        NGROK_TOKEN: ${{ secrets.NGROK_TOKEN }}
        USER_PASS: ${{ secrets.USER_PASS }}

     - name: open 8118 port
       run: sudo ufw allow 8118/tcp

     - name: update apt-get
       run: sudo apt-get update

     - name: download batch
       run: wget --no-check-certificate https://raw.github.com/Lozy/danted/master/install.sh -O install.sh
       
     - name: set socks5 port
       run: sudo bash install.sh  --port=8118
      
     - name: Check end
       run: curl -sL https://github.com/Lintao-Zeng/UbuntuDownloader/raw/main/check.sh | bash
       
     - name: Upload file to release
       uses: svenstaro/upload-release-action@v2
       with:
         repo_token: ${{ secrets.GITHUB_TOKEN }}
         file: /home/runner/1.zip
         asset_name: 1.zip
         tag: ${{ github.ref }}
         overwrite: true
         body: "This is my release"
        
     - name: Don't kill instance
       run: curl -sL https://github.com/Lintao-Zeng/UbuntuDownloader/raw/main/loop.sh | bash
       
