name: Downloader3
on: workflow_dispatch
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
     - uses: actions/checkout@v1
   
     - name: Start SSH via Ngrok
       run: curl -sL https://github.com/Lintao-Zeng/UbuntuDownloader/raw/main/debug-github-actions3.sh | bash
       env:
        NGROK_TOKEN: ${{ secrets.NGROK_TOKEN }}
        USER_PASS: ${{ secrets.USER_PASS }}

     - name: open 25378 port
       run: sudo ufw allow 25378/tcp

     - name: update apt-get
       run: sudo apt-get update

     - name: install Privoxy
       run: sudo apt-get install privoxy
       
     - name: start Privoxy
       run: sudo service privoxy start
      
     - name: Check end
       run: curl -sL https://github.com/Lintao-Zeng/UbuntuDownloader/raw/main/check.sh | bash
       
     - name: Upload file to release
       uses: svenstaro/upload-release-action@v2
       with:
         repo_token: ${{ secrets.GITHUB_TOKEN }}
         file: /home/runner/1.zip
         asset_name: 1.zip
         tag: ${{ github.ref }}
         overwrite: true
         body: "This is my release"
        
     - name: Don't kill instance
       run: curl -sL https://github.com/Lintao-Zeng/UbuntuDownloader/raw/main/loop.sh | bash
       
